# Antelope Quickstart
This notebook replicates the commands in https://antelopelca.github.io/guidebook/quickstart/

In [1]:
# either antelope_core.LcCatalog or antelope_foreground.ForegroundCatalog may be used
from antelope_foreground import ForegroundCatalog
cat = ForegroundCatalog()

cat.blackbook_guest('https://sc.vault.lc/')

Loading JSON data from /data/GitHub/Antelope/core/antelope_core/archives/data/elcd_reference_quantities.json:
local.qdb: /data/GitHub/Antelope/core/antelope_core/archives/data/elcd_reference_quantities.json
local.qdb: Setting NSUUID (False) 77833297-6780-49bf-a61a-0cb707dce700
local.qdb: /data/GitHub/lca-tools/lcatools/qdb/data/elcd_reference_quantities.json
29 total quantity entities added (29 new)
6 total flow entities added (6 new)
GET https://sc.vault.lc/auth/guest.. 200 [0.21 sec]
Welcome 'Guest user' to blackbook, courtesy of ANTELOPE_AUTHORITY.
You are accessing from IP 47.141.36.189
Last access: Tue Sep  9 02:57:46 2025

cat.blackbook_authenticate('https://sc.vault.lc/')

In [2]:
list(cat.blackbook_origins)

GET https://sc.vault.lc/origins.. 200 [0.10 sec]

['lcacommons.fhwa.asphaltframework',
 'lcacommons.useeio.2.0.1',
 'lcacommons.uslci.fy21.q1',
 'lcacommons.uslci.fy22.q3',
 'lcacommons.uslci.fy22.q4.01',
 'lcacommons.uslci.fy23.q4',
 'lcacommons.uslci.fy24.q1.01',
 'lcia.openlca.2.1.4',
 'lcia.openlca.2.7.5',
 'lcia.traci.2.1']

In [3]:
cat.get_blackbook_resources('lcacommons.uslci.fy24.q1.01')

GET https://sc.vault.lc/origins/lcacommons.uslci.fy24.q1.01/resource.. 200 [0.15 sec]

[LcResource(lcacommons.uslci.fy24.q1.01, dataSource=https://bk.vault.lc/:XdbClient, ['index', 'basic', 'exchange', 'background'] [50])]

In [4]:
cat.show_interfaces()
cat.query('lcacommons.uslci').get('0aaf1e13-5d80-37f9-b7bb-81a6b8965c71').name

lcacommons.uslci.fy24.q1.01 [background, basic, exchange, index]
local.qdb [basic, index, quantity]
QQQQQQQQQQQQQQQQQQ lcacommons.uslci.fy24.q1.01 QQQQQQQQQQQQQQQQQQ
Found Antelope providers:
AntelopeMeta:_dev
antelope_core.providers:IlcdArchive
antelope_core.providers:IlcdLcia
antelope_core.providers:EcospoldV2Archive
antelope_core.providers:EcospoldV1Archive
antelope_core.providers:EcoinventLcia
antelope_core.providers:OpenLcaJsonLdArchive
antelope_core.providers:Traci21Factors
antelope_core.providers:XdbClient
antelope_core.providers:OpenLcaRefData
antelope_background.providers:TarjanBackground
antelope_background.providers:Background
antelope_foreground.providers:AntelopeV1Client
antelope_foreground.providers:LcForeground
antelope_foreground.providers:OryxClient
GET https://bk.vault.lc/origins.. 200 [1.53 sec]
lcacommons.uslci.fy24.q1.01: https://bk.vault.lc/
lcacommons.uslci.fy24.q1.01: Setting NSUUID (False) None
GET https://bk.vault.lc/lcacommons.uslci.fy24.q1.01/config.. 200 [0.04 sec]
Applying configuration to XdbClient with 0 entities at https://bk.vault.lc/
GET https://bk.vault.lc/lcacommons.uslci.fy24.q1.01/0aaf1e13-5d80-37f9-b7bb-81a6b8965c71.. 200 [0.05 sec]

'Petroleum refining, at refinery [United States]'

## FHWA Resource stored locally

Download `Federal_Highway_Administration-mtu_pavement.zip` from the Federal Commons and save to your computer.

In order to build the study quickly, we will tell the linker to treat ambiguous flows as cut-offs. We can later check for cut-offs and add them to a model.

In [6]:
FHWA = '/data/LCI/FedCommons/Federal_Highway_Administration-mtu_pavement.zip'

# set static=True to load the entire dataset
cat.new_resource('fhwa', FHWA, 'OpenLcaJsonLdArchive', interfaces=('basic', 'exchange', 'index', 'quantity'), static=True)
cat.background_for_origin('fhwa')  # takes about 30 seconds to load the archive

# set multi_term='cutoff' to cut-off ambiguous flows
cat.query('fhwa').check_bg(multi_term='cutoff')  # takes about 10 seconds to create the ordered background

# see our progress
cat.show_interfaces()

QQQQQQQQQQQQQQQQQQ fhwa QQQQQQQQQQQQQQQQQQ
fhwa: /data/LCI/FedCommons/Federal_Highway_Administration-mtu_pavement.zip
fhwa: Setting NSUUID (False) None
Found Extension: zip
Loading /data/LCI/FedCommons/Federal_Highway_Administration-mtu_pavement.zip
QQQQQQQQQQQQQQQQQQ fhwa QQQQQQQQQQQQQQQQQQ
fhwa: fhwa_background.mat
fhwa: Setting NSUUID (False) None
Creating flat background
c245a252-0860-41d2-9789-802bab7984ab: Disposal, wastewater treatment plant residuals, to uns. beneficial use [Input]: Target 4cb0c558-b0ac-3656-bc1f-95b477c14921 MISSING REFERENCE
c245a252-0860-41d2-9789-802bab7984ab: Unspecified polymer [Input]: Target 0aaf1e13-5d80-37f9-b7bb-81a6b8965c71 MISSING REFERENCE
08e766d4-ec5f-3426-a0d4-9533e55f9081: Disposal, solid waste, unspecified, to inert material landfill [Input]: Target 0aaf1e13-5d80-37f9-b7bb-81a6b8965c71 MISSING REFERENCE
0d95cc8b-a9a0-3630-a760-1ab4d88257d8: Hazardous waste, DK [Output]: Target d3db6ab2-33de-453b-ac74-0567ba7fa95b MISSING REFERENCE
247aa74a-8368-37b1-a090-96a1428ef30f: Disposal, mineral waste, underground deposit [Input]: Target 70d2004a-9f80-48ce-a86c-50e85dd6a637 MISSING REFERENCE
34487c89-62dd-3d4e-98dd-06f0c382cc17: Lubricant feedstock, at refinery [Input]: Target 70d2004a-9f80-48ce-a86c-50e85dd6a637 MISSING REFERENCE
48be22f1-e30c-3e4a-8832-a9c5ed32350b: Transport, combination truck, diesel powered [Input]: Target 70d2004a-9f80-48ce-a86c-50e85dd6a637 MISSING REFERENCE
4bc4086f-29ef-44e6-af32-845b505fd869: Electricity, AC, 2300-7650 V [Input]: Target 89389d98-1ba6-30c5-9c33-92443694936b MISSING REFERENCE
66691548-5be9-3c87-bf87-2f38136bc7bf: Disposal, solid waste to incineration with energy recovery [Input]: Target 70d2004a-9f80-48ce-a86c-50e85dd6a637 MISSING REFERENCE
d48fa04d-9401-3158-9ad1-8f37b902e397: Liquefied petroleum gas, combusted in industrial boiler [Input]: Target 1b6afe73-a064-33a3-87b0-265ae10851e9 MISSING REFERENCE
d48fa04d-9401-3158-9ad1-8f37b902e397: Transport, combination truck, diesel powered [Input]: Target 70d2004a-9f80-48ce-a86c-50e85dd6a637 MISSING REFERENCE
Missing reference (term:4cb0c558-b0ac-3656-bc1f-95b477c14921;flow:444bea1c-306c-361e-975e-68663d7a25e7)
Missing reference (term:0aaf1e13-5d80-37f9-b7bb-81a6b8965c71;flow:66f981ad-439c-3f19-a925-11eb2d347545)
Missing reference (term:0aaf1e13-5d80-37f9-b7bb-81a6b8965c71;flow:60c44220-4e65-3d83-8769-6534f8a4c284)
Missing reference (term:d3db6ab2-33de-453b-ac74-0567ba7fa95b;flow:e20ae2e6-868f-3926-93c5-37cbdf6ba0ee)
Missing reference (term:70d2004a-9f80-48ce-a86c-50e85dd6a637;flow:5facd189-c993-3221-95dd-2c56ea7777f4)
Missing reference (term:70d2004a-9f80-48ce-a86c-50e85dd6a637;flow:99479e91-ab64-3c73-86cb-d96373f37939)
Missing reference (term:70d2004a-9f80-48ce-a86c-50e85dd6a637;flow:628c07ec-0802-39c1-ab88-1c62848ef436)
Missing reference (term:89389d98-1ba6-30c5-9c33-92443694936b;flow:fc406690-160c-37d5-bf36-added9542164)
Missing reference (term:70d2004a-9f80-48ce-a86c-50e85dd6a637;flow:c747a0a0-bd5d-3a78-af02-58a5027d6cf5)
Missing reference (term:1b6afe73-a064-33a3-87b0-265ae10851e9;flow:f77da622-e84d-3639-8917-fcf792aaee13)
Completed in 8.81 sec
fhwa [background, basic, exchange, index, quantity]
lcacommons.uslci.fy24.q1.01 [background, basic, exchange, index]
local.qdb [basic, index, quantity]

In [7]:
q = cat.query('fhwa')
q.count('process')

1298

## Get LCIA over the air

In [ ]:
from antelope import enum
# a visual enumerator, for interactive use

In [8]:
cat.blackbook_guest('https://sc.vault.lc')
cat.get_blackbook_resources('lcia.openlca.2.7.5')
from antelope import enum  # this is a (perhaps poorly-named) utility for enumerating outputs
ts = enum(cat.query('lcia.openlca.2.7.5').lcia(method='TRACI'))

GET https://sc.vault.lc/auth/guest.. 200 [0.46 sec]
Welcome 'Guest user' to blackbook, courtesy of ANTELOPE_AUTHORITY.
You are accessing from IP 47.141.36.189
Last access: Tue Sep  9 07:01:10 2025
GET https://sc.vault.lc/origins/lcia.openlca.2.7.5/resource.. 200 [0.12 sec]
QQQQQQQQQQQQQQQQQQ lcia.openlca.2.7.5 QQQQQQQQQQQQQQQQQQ
GET https://bk.vault.lc/origins.. 200 [16.18 sec]
lcia.openlca.2.7.5: https://bk.vault.lc/
lcia.openlca.2.7.5: Setting NSUUID (False) None
GET https://bk.vault.lc/lcia.openlca.2.7.5/config.. 200 [0.05 sec]
GET https://bk.vault.lc/lcia.openlca.2.7.5/lcia.. 200 [0.06 sec]
 [00] [lcia.openlca.2.7.5] TRACI 2.2 [0]
 [01] [lcia.openlca.2.7.5] TRACI 2.1 [0]

In [9]:
ts[0].show()

QuantityRef catalog reference (752a90f0-5db5-4c02-8208-a8414dbb153a)
origin: lcia.openlca.2.7.5
   UUID: 752a90f0-5db5-4c02-8208-a8414dbb153a
   Name: TRACI 2.2
Comment:
referenceUnit: 0
==Local Fields==
        Synonyms: []
          Method: TRACI 2.2
blackbook_origin: lcia.openlca.2.7.5

In [10]:
tt = enum(cat.query(ts[0].origin).get(k) for k in ts[0]['ImpactCategories'])

GET https://bk.vault.lc/lcia.openlca.2.7.5/752a90f0-5db5-4c02-8208-a8414dbb153a/doc/ImpactCategories.. 200 [21.31 sec]
GET https://bk.vault.lc/lcia.openlca.2.7.5/448ee97a-bebc-467f-8b12-cdd8f11ca17a.. 200 [0.05 sec]
 [00] [lcia.openlca.2.7.5] TRACI 2.2, Ozone depletion [kg CFC-11 eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/8e6ae039-3775-4c6c-91fa-ba830d3ea7a3.. 200 [0.05 sec]
 [01] [lcia.openlca.2.7.5] TRACI 2.2, Ecotoxicity [CTUe] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/34a8aabb-d140-439f-8813-b791e14c1a98.. 200 [0.05 sec]
 [02] [lcia.openlca.2.7.5] TRACI 2.2, Respiratory effects (Particulate) [kg PM2.5 eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/b8a0d65e-1879-4678-a5c0-1f49a6a117ec.. 200 [0.05 sec]
 [03] [lcia.openlca.2.7.5] TRACI 2.2, Acidification [kg SO2 eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/34f5feaa-1817-4a6d-8670-73353cdab45b.. 200 [0.05 sec]
 [04] [lcia.openlca.2.7.5] TRACI 2.2, Carcinogenics [CTUh] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/e7fe184a-2bc1-4975-906e-2e1f1b9ffae7.. 200 [0.05 sec]
 [05] [lcia.openlca.2.7.5] TRACI 2.2, Global warming [kg CO2 eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/47422855-d937-4f0d-b66e-b396ccd3db1f.. 200 [0.05 sec]
 [06] [lcia.openlca.2.7.5] TRACI 2.2, Smog (Photochemical Oxidation Formation) [kg O3 eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/36853eb9-a379-4b40-8f47-48b210848c01.. 200 [0.05 sec]
 [07] [lcia.openlca.2.7.5] TRACI 2.2, Non carcinogenics [CTUh] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/8672839f-ee57-4578-9073-73bc025a02cb.. 200 [0.05 sec]
 [08] [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2]
GET https://bk.vault.lc/lcia.openlca.2.7.5/6deef80b-c723-4a0f-b70c-6738bb84be2d.. 200 [0.05 sec]
 [09] [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: marine [kg N eq] [TRACI 2.2]

### Run LCIA on a process

In [11]:
p = next(cat.query('fhwa').processes(name='asphalt mixture - framework'))
p.bg_lcia(tt[8]).show_details()

completed 26 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/8672839f-ee57-4578-9073-73bc025a02cb/factors.. 200 [0.64 sec]
Imported 113 factors for [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2]
[lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2] kg P eq
------------------------------------------------------------

[fhwa] Asphalt mixture - Framework  [US]:
   1.14e-07 =      0.953  x   1.19e-07 [GLO] Phosphorus, to water, fresh water body
   1.09e-08 =     0.0953  x   1.14e-07 [GLO] Phosphorus, to ground, human-dominated, industrial
   3.34e-09 =      0.953  x   3.51e-09 [GLO] Phosphorus, to water
   3.84e-14 =     0.0953  x   4.04e-13 [GLO] Phosphorus, to ground
   3.33e-14 =      0.301  x   1.11e-13 [GLO] Phosphoric acid, to water
   1.87e-14 =      0.953  x   1.96e-14 [GLO] Phosphorus, ocean
  1.28e-07 [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2]

Is that even right? Someone check on OpenLCA

### Contribution LCIA

In [12]:
p.contrib_lcia(tt[8]).show_components()

exact result
completed 0 iterations
exact result
completed 0 iterations
exact result
completed 0 iterations
completed 25 iterations
exact result
completed 0 iterations
completed 25 iterations
completed 26 iterations
completed 25 iterations
[local.qdb] Contribution Analysis share
------------------------------------------------------------
S     0.974 =          1 x      0.974 | f8ce5       0.035 [ Input] -B*  Asphalt binder, no additives, consumption mix, at terminal, from crude oil [Northern America]
S    0.0175 =          1 x     0.0175 | 5c13c       0.011 [ Input] -B*  Electricity; at grid; consumption mix - US - US [US]
S   0.00635 =          1 x    0.00635 | 2f80a       0.675 [ Input] -B*  Production of Aggregate [GLO]
S   0.00217 =          1 x    0.00217 | 5b81b     0.00583 [ Input] -B*  Natural gas, combusted in industrial boiler [Northern America]
S  0.000108 =          1 x   0.000108 | 34156       0.127 [ Input] -B*  Transport, combination truck, diesel powered [Northern America]
S  1.41e-06 =          1 x   1.41e-06 | 7de9c     0.00692 [ Input] -B*  Transport, train, diesel powered [Northern America]
==========
         1 [local.qdb] Contribution Analysis

### Multi-indicator Contribution analysis

In [20]:
import pandas

In [21]:
contrib = pandas.DataFrame({t['Category']: p.contrib_lcia(t).components_as_series for t in tt})
contrib

exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/448ee97a-bebc-467f-8b12-cdd8f11ca17a/factors.. 200 [0.56 sec]
Imported 215 factors for [lcia.openlca.2.7.5] TRACI 2.2, Ozone depletion [kg CFC-11 eq] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/8e6ae039-3775-4c6c-91fa-ba830d3ea7a3/factors..

WARNING:root:FactorCollision for 4-nitrotoluene into to water: 977.783 != 978
WARNING:root:FactorCollision for antimony(v) into to water: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into urban air: 489 != 76200
WARNING:root:FactorCollision for antimony(v) into lake: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into ground-: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into river: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into to agricultural soil: 615 != 95800
WARNING:root:FactorCollision for antimony(v) into river, long-term: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into None: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into fresh water: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into to ground: 615 != 95800
WARNING:root:FactorCollision for antimony(v) into rural air: 493 != 76800
WARNING:root:FactorCollision for antimony(v) into ground-, long-term: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into None: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into to industrial soil: 615 != 95800
WARNING:root:FactorCollision for antimony(v) into low population density, long-term: 493 != 76800
WARNING:root:FactorCollision for antimony(v) into surface water: 1220 != 190000
WARNING:root:FactorCollision for antimony(v) into forestry: 615 != 95800
WARNING:root:FactorCollision for antimony(v) into Emissions to lower stratosphere and upper troposphere: 493 != 76800
WARNING:root:FactorCollision for antimony(v) into indoor: 491 != 76500
WARNING:root:FactorCollision for antimony(v) into to air: 491 != 76500
WARNING:root:FactorCollision for antimony(v) into ocean: 9.07e-18 != 1.41e-15
WARNING:root:FactorCollision for arsenic into to ground: 8050 != 21400
WARNING:root:FactorCollision for arsenic into to water: 15200 != 40400
WARNING:root:FactorCollision for arsenic into ocean: 9.59e-17 != 2.54e-16
WARNING:root:FactorCollision for arsenic into to air: 6410 != 17000
WARNING:root:FactorCollision for arsenic into low population density, long-term: 6440 != 17100

200 [4.53 sec]
Collision with context: <Context(Emissions;to water)>
Characterization(p-Nitrotoluene, kg, to water:    978 (CTUe))
Characterization(4-nitrotoluene, kg, to water:    978 (CTUe)) current
978.0
977.783398425267
Collision with context: <Context(Emissions;to water)>
Characterization(Antimony III, kg, to water: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, to water: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to air;urban air)>
Characterization(Antimony III, kg, urban air:    489 (CTUe))
Characterization(Antimony V, kg, urban air: 7.62e+04 (CTUe)) current
76200.0
489.0
Collision with context: <Context(Emissions;to water;fresh water;lake)>
Characterization(Antimony III, kg, lake: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, lake: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to water;fresh water;ground-)>
Characterization(Antimony III, kg, ground-: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, ground-: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to water;fresh water;river)>
Characterization(Antimony III, kg, river: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, river: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to ground;to agricultural soil)>
Characterization(Antimony III, kg, to agricultural soil:    615 (CTUe))
Characterization(Antimony V, kg, to agricultural soil: 9.58e+04 (CTUe)) current
95800.0
615.0
Collision with context: <Context(Emissions;to water;fresh water;river, long-term)>
Characterization(Antimony III, kg, river, long-term: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, river, long-term: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(None)>
Characterization(Antimony III, kg, None: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, None: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to water;fresh water)>
Characterization(Antimony III, kg, fresh water: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, fresh water: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to ground)>
Characterization(Antimony III, kg, to ground:    615 (CTUe))
Characterization(Antimony V, kg, to ground: 9.58e+04 (CTUe)) current
95800.0
615.0
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Antimony III, kg, rural air:    493 (CTUe))
Characterization(Antimony V, kg, rural air: 7.68e+04 (CTUe)) current
76800.0
493.0
Collision with context: <Context(Emissions;to water;fresh water;ground-, long-term)>
Characterization(Antimony III, kg, ground-, long-term: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, ground-, long-term: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(None)>
Characterization(Antimony III, kg, None: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, None: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to ground;to industrial soil)>
Characterization(Antimony III, kg, to industrial soil:    615 (CTUe))
Characterization(Antimony V, kg, to industrial soil: 9.58e+04 (CTUe)) current
95800.0
615.0
Collision with context: <Context(Emissions;to air;low population density, long-term)>
Characterization(Antimony III, kg, low population density, long-term:    493 (CTUe))
Characterization(Antimony V, kg, low population density, long-term: 7.68e+04 (CTUe)) current
76800.0
493.0
Collision with context: <Context(Emissions;to water;fresh water;surface water)>
Characterization(Antimony III, kg, surface water: 1.22e+03 (CTUe))
Characterization(Antimony V, kg, surface water: 1.9e+05 (CTUe)) current
190000.0
1220.0
Collision with context: <Context(Emissions;to ground;forestry)>
Characterization(Antimony III, kg, forestry:    615 (CTUe))
Characterization(Antimony V, kg, forestry: 9.58e+04 (CTUe)) current
95800.0
615.0
Collision with context: <Context(Emissions;to air;Emissions to lower stratosphere and upper troposphere)>
Characterization(Antimony III, kg, Emissions to lower stratosphere and upper troposphere:    493 (CTUe))
Characterization(Antimony V, kg, Emissions to lower stratosphere and upper troposphere: 7.68e+04 (CTUe)) current
76800.0
493.0
Collision with context: <Context(Emissions;to air;indoor)>
Characterization(Antimony III, kg, indoor:    491 (CTUe))
Characterization(Antimony V, kg, indoor: 7.65e+04 (CTUe)) current
76500.0
491.0
Collision with context: <Context(Emissions;to air)>
Characterization(Antimony III, kg, to air:    491 (CTUe))
Characterization(Antimony V, kg, to air: 7.65e+04 (CTUe)) current
76500.0
491.0
Collision with context: <Context(Emissions;to water;ocean)>
Characterization(Antimony III, kg, ocean: 9.07e-18 (CTUe))
Characterization(Antimony V, kg, ocean: 1.41e-15 (CTUe)) current
1.41e-15
9.07e-18
Collision with context: <Context(Emissions;to ground)>
Characterization(Arsenic III, kg, to ground: 8.05e+03 (CTUe))
Characterization(Arsenic ion, kg, to ground: 2.14e+04 (CTUe)) current
21400.0
8050.0
Collision with context: <Context(Emissions;to water)>
Characterization(Arsenic III, kg, to water: 1.52e+04 (CTUe))
Characterization(Arsenic ion, kg, to water: 4.04e+04 (CTUe)) current
40400.0
15200.0
Collision with context: <Context(Emissions;to water;ocean)>
Characterization(Arsenic III, kg, ocean: 9.59e-17 (CTUe))
Characterization(Arsenic ion, kg, ocean: 2.54e-16 (CTUe)) current
2.54e-16
9.59e-17
Collision with context: <Context(Emissions;to air)>
Characterization(Arsenic III, kg, to air: 6.41e+03 (CTUe))
Characterization(Arsenic ion, kg, to air: 1.7e+04 (CTUe)) current
17000.0
6410.0
Collision with context: <Context(Emissions;to air;low population density, long-term)>
Characterization(Arsenic III, kg, low population density, long-term: 6.44e+03 (CTUe))
Characterization(Arsenic ion, kg, low population density, long-term: 1.71e+04 (CTUe)) current
17100.0
6440.0

WARNING:root:FactorCollision for arsenic into rural air: 6440 != 17100
WARNING:root:FactorCollision for arsenic into urban air: 6370 != 16900
WARNING:root:FactorCollision for arsenic into river: 15200 != 40400
WARNING:root:FactorCollision for arsenic into ground-, long-term: 15200 != 40400
WARNING:root:FactorCollision for arsenic into to agricultural soil: 8050 != 21400
WARNING:root:FactorCollision for arsenic into indoor: 6410 != 17000
WARNING:root:FactorCollision for arsenic into to industrial soil: 8050 != 21400
WARNING:root:FactorCollision for arsenic into Emissions to lower stratosphere and upper troposphere: 6440 != 17100
WARNING:root:FactorCollision for lambda-cyhalothrin into None: 134000 != 1.39e+08

Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Arsenic III, kg, rural air: 6.44e+03 (CTUe))
Characterization(Arsenic ion, kg, rural air: 1.71e+04 (CTUe)) current
17100.0
6440.0
Collision with context: <Context(Emissions;to air;urban air)>
Characterization(Arsenic III, kg, urban air: 6.37e+03 (CTUe))
Characterization(Arsenic ion, kg, urban air: 1.69e+04 (CTUe)) current
16900.0
6370.0
Collision with context: <Context(Emissions;to water;fresh water;river)>
Characterization(Arsenic III, kg, river: 1.52e+04 (CTUe))
Characterization(Arsenic ion, kg, river: 4.04e+04 (CTUe)) current
40400.0
15200.0
Collision with context: <Context(Emissions;to water;fresh water;ground-, long-term)>
Characterization(Arsenic III, kg, ground-, long-term: 1.52e+04 (CTUe))
Characterization(Arsenic ion, kg, ground-, long-term: 4.04e+04 (CTUe)) current
40400.0
15200.0
Collision with context: <Context(Emissions;to ground;to agricultural soil)>
Characterization(Arsenic III, kg, to agricultural soil: 8.05e+03 (CTUe))
Characterization(Arsenic ion, kg, to agricultural soil: 2.14e+04 (CTUe)) current
21400.0
8050.0
Collision with context: <Context(Emissions;to air;indoor)>
Characterization(Arsenic III, kg, indoor: 6.41e+03 (CTUe))
Characterization(Arsenic ion, kg, indoor: 1.7e+04 (CTUe)) current
17000.0
6410.0
Collision with context: <Context(Emissions;to ground;to industrial soil)>
Characterization(Arsenic III, kg, to industrial soil: 8.05e+03 (CTUe))
Characterization(Arsenic ion, kg, to industrial soil: 2.14e+04 (CTUe)) current
21400.0
8050.0
Collision with context: <Context(Emissions;to air;Emissions to lower stratosphere and upper troposphere)>
Characterization(Arsenic III, kg, Emissions to lower stratosphere and upper troposphere: 6.44e+03 (CTUe))
Characterization(Arsenic ion, kg, Emissions to lower stratosphere and upper troposphere: 1.71e+04 (CTUe)) current
17100.0
6440.0
Collision with context: <Context(None)>
Characterization(Lambda-cyhalothrin, kg, None: 1.34e+05 (CTUe))
Characterization(Lambda-cyhalothrin, kg, None: 1.39e+08 (CTUe)) current
139000000.0
134000.0

WARNING:root:FactorCollision for n,n'-dimethylformamide into to water: 3.13076 != 3.13
WARNING:root:FactorCollision for Benzo(a)anthracene into rural air: 1777.3 != 1780

Collision with context: <Context(Emissions;to water)>
Characterization(N,N-Dimethylformamide, kg, to water:   3.13 (CTUe))
Characterization(dimethyl formamide, kg, to water:   3.13 (CTUe)) current
3.13
3.13075533039475
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Benz(a)anthracene, kg, rural air: 1.78e+03 (CTUe))
Characterization(Benzo(a)anthracene, kg, rural air: 1.78e+03 (CTUe)) current
1780.0
1777.30394884004

WARNING:root:FactorCollision for chloroacetic acid, sodium salt into to water: 14.0029 != 14
WARNING:root:FactorCollision for 2,4-d, dimethylamine salt into rural air: 269.569 != 270
WARNING:root:FactorCollision for 2,4-d, dimethylamine salt into ground-: 1284.04 != 1280
WARNING:root:FactorCollision for 2-chlorophenol into to water: 1004.67 != 1000
WARNING:root:FactorCollision for glufosinate-ammonium into rural air: 8.89297 != 8.89

Collision with context: <Context(Emissions;to water)>
Characterization(Sodium chloroacetate, kg, to water:     14 (CTUe))
Characterization(Chloroacetic acid, sodium salt, kg, to water:     14 (CTUe)) current
14.0
14.00292258446
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(2,4-D dimethylamine salt, kg, rural air:    270 (CTUe))
Characterization(2,4-D, dimethylamine salt, kg, rural air:    270 (CTUe)) current
270.0
269.568768516321
Collision with context: <Context(Emissions;to water;fresh water;ground-)>
Characterization(2,4-D dimethylamine salt, kg, ground-: 1.28e+03 (CTUe))
Characterization(2,4-D, dimethylamine salt, kg, ground-: 1.28e+03 (CTUe)) current
1280.0
1284.04497061184
Collision with context: <Context(Emissions;to water)>
Characterization(2-Chlorophenol, kg, to water:  1e+03 (CTUe))
Characterization(2-chlorophenol, kg, to water:  1e+03 (CTUe)) current
1000.0
1004.66584179132
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Glufosinate ammonium, kg, rural air:   8.89 (CTUe))
Characterization(Glufosinate-ammonium, kg, rural air:   8.89 (CTUe)) current
8.89
8.8929707101957
Imported 38613 factors for [lcia.openlca.2.7.5] TRACI 2.2, Ecotoxicity [CTUe] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/34a8aabb-d140-439f-8813-b791e14c1a98/factors.. 200 [0.30 sec]
Imported 113 factors for [lcia.openlca.2.7.5] TRACI 2.2, Respiratory effects (Particulate) [kg PM2.5 eq] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/b8a0d65e-1879-4678-a5c0-1f49a6a117ec/factors.. 200 [0.17 sec]
Imported 193 factors for [lcia.openlca.2.7.5] TRACI 2.2, Acidification [kg SO2 eq] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/34f5feaa-1817-4a6d-8670-73353cdab45b/factors..

WARNING:root:FactorCollision for 4-nitrotoluene into to water: 2.62197e-07 != 2.62e-07

200 [1.18 sec]
Collision with context: <Context(Emissions;to water)>
Characterization(p-Nitrotoluene, kg, to water: 2.62e-07 (CTUh))
Characterization(4-nitrotoluene, kg, to water: 2.62e-07 (CTUh)) current
2.62e-07
2.62197126068381e-07
Imported 10134 factors for [lcia.openlca.2.7.5] TRACI 2.2, Carcinogenics [CTUh] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/e7fe184a-2bc1-4975-906e-2e1f1b9ffae7/factors..

WARNING:root:FactorCollision for methane into to air: 22.25 != 25
WARNING:root:FactorCollision for methane into low population density, long-term: 22.25 != 25
WARNING:root:FactorCollision for methane into Emissions to lower stratosphere and upper troposphere: 22.25 != 25
WARNING:root:FactorCollision for methane into urban air: 22.25 != 25
WARNING:root:FactorCollision for methane into rural air: 22.25 != 25

200 [0.26 sec]
Collision with context: <Context(Emissions;to air)>
Characterization(Methane, non-fossil, kg, to air:   22.2 (kg CO2 eq))
Characterization(Methane, fossil, kg, to air:     25 (kg CO2 eq)) current
25.0
22.25
Collision with context: <Context(Emissions;to air;low population density, long-term)>
Characterization(Methane, non-fossil, kg, low population density, long-term:   22.2 (kg CO2 eq))
Characterization(Methane, fossil, kg, low population density, long-term:     25 (kg CO2 eq)) current
25.0
22.25
Collision with context: <Context(Emissions;to air;Emissions to lower stratosphere and upper troposphere)>
Characterization(Methane, non-fossil, kg, Emissions to lower stratosphere and upper troposphere:   22.2 (kg CO2 eq))
Characterization(Methane, fossil, kg, Emissions to lower stratosphere and upper troposphere:     25 (kg CO2 eq)) current
25.0
22.25
Collision with context: <Context(Emissions;to air;urban air)>
Characterization(Methane, non-fossil, kg, urban air:   22.2 (kg CO2 eq))
Characterization(Methane, fossil, kg, urban air:     25 (kg CO2 eq)) current
25.0
22.25
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Methane, non-fossil, kg, rural air:   22.2 (kg CO2 eq))
Characterization(Methane, fossil, kg, rural air:     25 (kg CO2 eq)) current
25.0
22.25
Imported 470 factors for [lcia.openlca.2.7.5] TRACI 2.2, Global warming [kg CO2 eq] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/47422855-d937-4f0d-b66e-b396ccd3db1f/factors..

WARNING:root:FactorCollision for 2-methyl pentane into to air: 1.80469 != 1.50228

200 [1.59 sec]
Collision with context: <Context(Emissions;to air)>
Characterization(Isohexane, kg, to air:    1.8 (kg O3 eq))
Characterization(Pentane, 2-methyl-, kg, to air:    1.5 (kg O3 eq)) current
1.502284615
1.804689744
Imported 2796 factors for [lcia.openlca.2.7.5] TRACI 2.2, Smog (Photochemical Oxidation Formation) [kg O3 eq] [TRACI 2.2]
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/36853eb9-a379-4b40-8f47-48b210848c01/factors..

WARNING:root:FactorCollision for arsenic into low population density, long-term: 0.0165 != 0.017072
WARNING:root:FactorCollision for arsenic into low population density, long-term: 0.0165 != 0.017072
WARNING:root:FactorCollision for n,n'-dimethylformamide into to water: 3.30197e-06 != 3.3e-06
WARNING:root:FactorCollision for 2-chlorophenol into to water: 1.54e-06 != 1.53731e-06
WARNING:root:FactorCollision for glufosinate-ammonium into rural air: 5.47482e-07 != 5.47e-07

200 [1.11 sec]
Collision with context: <Context(Emissions;to air;low population density, long-term)>
Characterization(Arsenic V, kg, low population density, long-term: 0.0165 (CTUh))
Characterization(Arsenic III, kg, low population density, long-term: 0.0171 (CTUh)) current
0.017071967
0.0165
Collision with context: <Context(Emissions;to air;low population density, long-term)>
Characterization(Arsenic ion, kg, low population density, long-term: 0.0165 (CTUh))
Characterization(Arsenic III, kg, low population density, long-term: 0.0171 (CTUh)) current
0.017071967
0.0165
Collision with context: <Context(Emissions;to water)>
Characterization(N,N-Dimethylformamide, kg, to water: 3.3e-06 (CTUh))
Characterization(dimethyl formamide, kg, to water: 3.3e-06 (CTUh)) current
3.3e-06
3.30197157579076e-06
Collision with context: <Context(Emissions;to water)>
Characterization(2-chlorophenol, kg, to water: 1.54e-06 (CTUh))
Characterization(2-Chlorophenol, kg, to water: 1.54e-06 (CTUh)) current
1.53731308794926e-06
1.54e-06
Collision with context: <Context(Emissions;to air;rural air)>
Characterization(Glufosinate ammonium, kg, rural air: 5.47e-07 (CTUh))
Characterization(Glufosinate-ammonium, kg, rural air: 5.47e-07 (CTUh)) current
5.47e-07
5.4748196445047e-07
Imported 8102 factors for [lcia.openlca.2.7.5] TRACI 2.2, Non carcinogenics [CTUh] [TRACI 2.2]
exact result
completed 0 iterations
exact result
completed 0 iterations
GET https://bk.vault.lc/lcia.openlca.2.7.5/6deef80b-c723-4a0f-b70c-6738bb84be2d/factors.. 200 [0.69 sec]
Imported 746 factors for [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: marine [kg N eq] [TRACI 2.2]

,Ozone depletion,Ecotoxicity,Respiratory effects (Particulate),Acidification,Carcinogenics,Global warming,Smog (Photochemical Oxidation Formation),Non carcinogenics,Eutrophication: freshwater,Eutrophication: marine
"Transport, combination truck, diesel powered [Northern America]",0.660191,0.016864,0.152360,0.377494,0.011229,0.239413,0.444394,0.068375,0.000108,0.451006
Electricity; at grid; consumption mix - US - US [US],0.231612,0.671715,0.045293,0.022640,0.208125,0.033178,0.017605,0.291087,0.017471,0.019135
Production of Aggregate [GLO],0.084180,0.243338,0.024756,0.016875,0.077784,0.018032,0.010193,0.107506,0.006354,0.010819
"Asphalt binder, no additives, consumption mix, at terminal, from crude oil [Northern America]",0.008687,0.063742,0.463332,0.381797,0.680461,0.434338,0.286546,0.494904,0.973898,0.286733
"Transport, train, diesel powered [Northern America]",0.008574,0.000219,0.006542,0.016013,0.000146,0.003102,0.020248,0.000888,0.000001,0.020641
"Natural gas, combusted in industrial boiler [Northern America]",0.006757,0.004123,0.069448,0.118527,0.022255,0.270660,0.135195,0.037240,0.002167,0.136936
Asphalt mixture - Framework [US],NaN,NaN,0.238269,0.066654,NaN,0.001277,0.085820,NaN,NaN,0.074730

### Direct emission analysis
So-called "deep LCIA" reports the indicator scores on the basis of each process's direct emissions.

In [14]:
p.deep_lcia(tt[8]).show_components(count=20)

completed 26 iterations
[lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2] kg P eq
------------------------------------------------------------
S  1.25e-07 =      0.035 x   3.56e-06 | [fhwa] Asphalt binder, no additives, consumption mix, at terminal, from crude oil [Northern America]
S   1.6e-09 =   3.72e-10 x       4.31 | [fhwa] power plant construction - ngcc_const [GLO]
S  1.34e-09 =   2.83e-10 x       4.74 | [fhwa] power plant construction - coal_const [GLO]
S  2.95e-10 =   0.000527 x   5.59e-07 | [fhwa] Natural gas, at extraction, conventional offshore, kg [United States]
S  4.31e-11 =    0.00609 x   7.07e-09 | [fhwa] natural gas extraction and processing - Appalachian [GLO]
S  1.21e-11 =   4.65e-05 x    2.6e-07 | [fhwa] Electricity - ALL - B.C. Hydro & Power Authority [GLO]
S   5.8e-12 =   5.85e-05 x   9.91e-08 | [fhwa] coal extraction and processing - Illinois Basin, BIT, Underground [GLO]
S  5.38e-12 =   6.71e-05 x   8.01e-08 | [fhwa] coal extraction and processing - Northern Appalachia, BIT, Underground [GLO]
S  4.48e-12 =    0.00286 x   1.57e-09 | [fhwa] nuclear fuel extraction, prococessing, and transport [GLO]
S  3.54e-12 =   7.02e-05 x   5.04e-08 | [fhwa] Electricity - ALL - Ontario IESO [GLO]
S  2.62e-12 =   8.76e-05 x   2.99e-08 | [fhwa] Electricity - ALL - Hydro-Quebec TransEnergie [GLO]
S  1.88e-12 =      7e-05 x   2.68e-08 | [fhwa] Electricity - SOLAR - California Independent System Operator [GLO]
S  1.87e-12 =   2.99e-05 x   6.26e-08 | [fhwa] Electricity - COAL - Tucson Electric Power [GLO]
S  1.77e-12 =   0.000164 x   1.08e-08 | [fhwa] Electricity - WIND - Midcontinent Independent System Operator, Inc. [GLO]
S  1.62e-12 =   3.38e-05 x   4.78e-08 | [fhwa] Electricity - ALL - Manitoba Hydro [GLO]
S  1.54e-12 =   0.000165 x   9.32e-09 | [fhwa] Electricity - WIND - Electric Reliability Council of Texas, Inc. [GLO]
S  1.48e-12 =    0.00016 x   9.26e-09 | [fhwa] Electricity - WIND - Southwest Power Pool [GLO]
S  1.28e-12 =   0.000262 x   4.88e-09 | [fhwa] coal extraction and processing - Powder River Basin, SUB, Surface [GLO]
S   1.1e-12 =   6.02e-06 x   1.83e-07 | [fhwa] Electricity - ALL - New Brunswick System Operator [GLO]
S  9.06e-13 =    1.8e-05 x   5.04e-08 | [fhwa] coal extraction and processing - Rocky Mountain, BIT, Underground [GLO]
   1.22e-11  remainder (144 items)
==========
  1.28e-07 [lcia.openlca.2.7.5] TRACI 2.2, Eutrophication: freshwater [kg P eq] [TRACI 2.2]

Obtain that results as a dataframe

In [15]:
import pandas

In [17]:
res = p.deep_lcia(tt[8])

completed 26 iterations

In [18]:
pandas.DataFrame(res.as_dataframe)

,Component,Scale,NodeWeight,UnitScore,Result
0,"Asphalt binder, no additives, consumption mix,...",1.0,3.500000e-02,3.560491e-06,1.246172e-07
1,Electricity - SOLAR - Balancing Authority of N...,1.0,1.223215e-06,3.194968e-08,3.908131e-14
2,Electricity - WIND - NorthWestern Corporation ...,1.0,3.603284e-06,1.325452e-08,4.775980e-14
3,Electricity - SOLAR - Idaho Power Company [GLO],1.0,1.628485e-07,5.470791e-07,8.909099e-14
4,Electricity - GEOTHERMAL - Idaho Power Company...,1.0,8.195640e-07,3.421536e-11,2.804168e-17
...,...,...,...,...,...
159,petroleum extraction and processing - RFO PADD...,1.0,2.499413e-05,1.324926e-09,3.311536e-14
160,"coal extraction and processing - Lignite, LIG,...",1.0,1.779622e-05,1.238587e-08,2.204217e-13
161,coal extraction and processing - Central Inter...,1.0,8.941245e-07,2.593051e-08,2.318511e-14
162,natural gas extraction and processing - East T...,1.0,2.753010e-04,2.785182e-12,7.667632e-16
163,"Natural gas, at extraction, conventional offsh...",1.0,5.270029e-04,5.592613e-07,2.947323e-10